name: 'Set up Go'
description: 'Install Go and set up cache'
inputs:
  cache-key-prefix:
    description: 'Cache key prefix'
    required: false
    default: setup-go-with-cache-${{ github.workflow }}-${{ github.job }}
runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v6.1.0
      with:
        go-version-file: .go-version
    - name: Get Go cache paths
      id: go-cache
      shell: bash
      run: |-
        gocache=$(go env GOCACHE)
        gomodcache=$(go env GOMODCACHE)
        cat >>"$GITHUB_OUTPUT" <<EOF
        cache=$gocache
        modcache=$gomodcache
        EOF
    - name: Set up Go cache
      uses: actions/cache@v4.3.0
      with:
        key: |-
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |-
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ github.run_id }}-
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-
        path: |-
          ${{ steps.go-cache.outputs.cache }}
          ${{ steps.go-cache.outputs.modcache }}
