// Command tutorial is the finished program from the plumb tutorial in README.md.
// It is a tiny greeter whose wiring, the build function, is generated by plumb.
//
//	go run .              # greets with "Hi there!" (unless the greeter is grumpy)
//	go run . "Welcome!"   # greets with your own phrase
package main

import (
	"fmt"
	"os"
)

func main() {
	phrase := Phrase("Hi there!")
	if len(os.Args) > 1 {
		phrase = Phrase(os.Args[1])
	}

	// build is generated in plumb_gen.go. plumb inferred its signature from the
	// providers. It takes the Phrase that no provider produces, returns the Event
	// that no provider consumes, and passes through the error NewEvent can return.
	event, err := build(phrase)
	if err != nil {
		fmt.Println("no event today:", err)
		return
	}
	event.Start()
}
