// Code generated by plumb. DO NOT EDIT.

package main

func build(phrase Phrase) (event Event, err error) {
	message := NewMessage(phrase)
	greeter := NewGreeter(message)
	event2, e := NewEvent(greeter)
	if e != nil {
		err = e
		return
	}
	event = event2
	return
}
