run:
  timeout: 5m

linters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: go.pact.im
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - log
    packages-with-error-message:
      - log: "use go.uber.org/zap instead"

linters:
  enable:
    - gofumpt
    - goimports
    - depguard
    - gocritic
    - misspell
    - revive
    - unparam
  disable:
    # False positives for embedded structs.
    # See https://github.com/golangci/golangci-lint/issues/1841
    # and https://gitlab.com/opennota/check/-/issues/11
    - structcheck

issues:
  exclude-use-default: false
