version: "2"
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(golang.org/,google.golang.org/)
        - default # third-party with custom import path
        - prefix(github.com/,gitlab.com/)
        - prefix(go.pact.im/x/)
        - localmodule
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - gomoddirectives
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unparam
    - unused
    - usestdlibvars
  settings:
    staticcheck:
      checks:
        - all
    revive:
      confidence: 0
    nolintlint:
      # Forbid nolint directives without explanation comment and specific linter.
      require-explanation: true
      require-specific: true
    misspell:
      locale: US
    gomoddirectives:
      go-version-pattern: "1\\.24\\.0"
      toolchain-forbidden: true
      replace-local: true # for tests
