// Code generated by MockGen. DO NOT EDIT.
// Source: go.pact.im/x/httprange (interfaces: Ranger)
//
// Generated by this command:
//
//	mockgen -package=httprange -destination=mockranger_test.go -write_package_comment=false go.pact.im/x/httprange Ranger
//

package httprange

import (
	context "context"
	iter "iter"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRanger is a mock of Ranger interface.
type MockRanger struct {
	ctrl     *gomock.Controller
	recorder *MockRangerMockRecorder
	isgomock struct{}
}

// MockRangerMockRecorder is the mock recorder for MockRanger.
type MockRangerMockRecorder struct {
	mock *MockRanger
}

// NewMockRanger creates a new mock instance.
func NewMockRanger(ctrl *gomock.Controller) *MockRanger {
	mock := &MockRanger{ctrl: ctrl}
	mock.recorder = &MockRangerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRanger) EXPECT() *MockRangerMockRecorder {
	return m.recorder
}

// Range mocks base method.
func (m *MockRanger) Range(ctx context.Context, spec Specifier) iter.Seq2[Range, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Range", ctx, spec)
	ret0, _ := ret[0].(iter.Seq2[Range, error])
	return ret0
}

// Range indicates an expected call of Range.
func (mr *MockRangerMockRecorder) Range(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockRanger)(nil).Range), ctx, spec)
}
