// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Cloud API Gateway. For more information, see the official documentation
// [Yandex Cloud API Gateway](https://cloud.yandex.com/docs/api-gateway/).
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"go.pact.im/x/tf2pulumi/yandex"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err = yandex.LookupApiGateway(ctx, &GetApiGatewayArgs{
// 			Name: pulumi.StringRef("my-api-gateway"),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupApiGateway(ctx *pulumi.Context, args *LookupApiGatewayArgs, opts ...pulumi.InvokeOption) (*LookupApiGatewayResult, error) {
	var rv LookupApiGatewayResult
	err := ctx.Invoke("yandex:index/getApiGateway:getApiGateway", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApiGateway.
type LookupApiGatewayArgs struct {
	// Yandex Cloud API Gateway id used to define api gateway.
	ApiGatewayId *string `pulumi:"apiGatewayId"`
	// Folder ID for the Yandex Cloud API Gateway.
	FolderId *string `pulumi:"folderId"`
	// Yandex Cloud API Gateway name used to define api gateway.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getApiGateway.
type LookupApiGatewayResult struct {
	ApiGatewayId *string `pulumi:"apiGatewayId"`
	// Creation timestamp of the Yandex Cloud API Gateway.
	CreatedAt string `pulumi:"createdAt"`
	// Description of the Yandex Cloud API Gateway.
	Description string `pulumi:"description"`
	// Default domain for the Yandex API Gateway.
	Domain   string  `pulumi:"domain"`
	FolderId *string `pulumi:"folderId"`
	Id       string  `pulumi:"id"`
	// A set of key/value label pairs to assign to the Yandex Cloud API Gateway.
	Labels     map[string]string `pulumi:"labels"`
	LogGroupId string            `pulumi:"logGroupId"`
	Name       *string           `pulumi:"name"`
	// Status of the Yandex API Gateway.
	Status string `pulumi:"status"`
	// Set of user domains attached to Yandex API Gateway.
	UserDomains []string `pulumi:"userDomains"`
}

func LookupApiGatewayOutput(ctx *pulumi.Context, args LookupApiGatewayOutputArgs, opts ...pulumi.InvokeOption) LookupApiGatewayResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupApiGatewayResult, error) {
			args := v.(LookupApiGatewayArgs)
			r, err := LookupApiGateway(ctx, &args, opts...)
			var s LookupApiGatewayResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupApiGatewayResultOutput)
}

// A collection of arguments for invoking getApiGateway.
type LookupApiGatewayOutputArgs struct {
	// Yandex Cloud API Gateway id used to define api gateway.
	ApiGatewayId pulumi.StringPtrInput `pulumi:"apiGatewayId"`
	// Folder ID for the Yandex Cloud API Gateway.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// Yandex Cloud API Gateway name used to define api gateway.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupApiGatewayOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApiGatewayArgs)(nil)).Elem()
}

// A collection of values returned by getApiGateway.
type LookupApiGatewayResultOutput struct{ *pulumi.OutputState }

func (LookupApiGatewayResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApiGatewayResult)(nil)).Elem()
}

func (o LookupApiGatewayResultOutput) ToLookupApiGatewayResultOutput() LookupApiGatewayResultOutput {
	return o
}

func (o LookupApiGatewayResultOutput) ToLookupApiGatewayResultOutputWithContext(ctx context.Context) LookupApiGatewayResultOutput {
	return o
}

func (o LookupApiGatewayResultOutput) ApiGatewayId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) *string { return v.ApiGatewayId }).(pulumi.StringPtrOutput)
}

// Creation timestamp of the Yandex Cloud API Gateway.
func (o LookupApiGatewayResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Description of the Yandex Cloud API Gateway.
func (o LookupApiGatewayResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.Description }).(pulumi.StringOutput)
}

// Default domain for the Yandex API Gateway.
func (o LookupApiGatewayResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.Domain }).(pulumi.StringOutput)
}

func (o LookupApiGatewayResultOutput) FolderId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) *string { return v.FolderId }).(pulumi.StringPtrOutput)
}

func (o LookupApiGatewayResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.Id }).(pulumi.StringOutput)
}

// A set of key/value label pairs to assign to the Yandex Cloud API Gateway.
func (o LookupApiGatewayResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupApiGatewayResultOutput) LogGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.LogGroupId }).(pulumi.StringOutput)
}

func (o LookupApiGatewayResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// Status of the Yandex API Gateway.
func (o LookupApiGatewayResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.Status }).(pulumi.StringOutput)
}

// Set of user domains attached to Yandex API Gateway.
func (o LookupApiGatewayResultOutput) UserDomains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) []string { return v.UserDomains }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupApiGatewayResultOutput{})
}
