// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Cloud Logging group. For more information,
// see [the official documentation](https://cloud.yandex.com/en/docs/logging/concepts/log-group).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"go.pact.im/x/tf2pulumi/yandex"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		myGroup, err := yandex.LookupLoggingGroup(ctx, &GetLoggingGroupArgs{
// 			GroupId: pulumi.StringRef("some_yandex_logging_group_id"),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("logGroupRetentionPeriod", myGroup.RetentionPeriod)
// 		return nil
// 	})
// }
// ```
func LookupLoggingGroup(ctx *pulumi.Context, args *LookupLoggingGroupArgs, opts ...pulumi.InvokeOption) (*LookupLoggingGroupResult, error) {
	var rv LookupLoggingGroupResult
	err := ctx.Invoke("yandex:index/getLoggingGroup:getLoggingGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLoggingGroup.
type LookupLoggingGroupArgs struct {
	// ID of the folder that the Yandex Cloud Logging group belongs to.
	// It will be deduced from provider configuration if not set explicitly.
	FolderId *string `pulumi:"folderId"`
	// The Yandex Cloud Logging group ID.
	GroupId *string `pulumi:"groupId"`
	// The Yandex Cloud Logging group name.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getLoggingGroup.
type LookupLoggingGroupResult struct {
	// ID of the cloud that the Yandex Cloud Logging group belong to.
	CloudId string `pulumi:"cloudId"`
	// The Yandex Cloud Logging group creation timestamp.
	CreatedAt string `pulumi:"createdAt"`
	// The Yandex Cloud Logging group description.
	Description string `pulumi:"description"`
	FolderId    string `pulumi:"folderId"`
	GroupId     string `pulumi:"groupId"`
	Id          string `pulumi:"id"`
	// A set of key/value label pairs assigned to the Yandex Cloud Logging group.
	Labels map[string]string `pulumi:"labels"`
	Name   string            `pulumi:"name"`
	// The Yandex Cloud Logging group log entries retention period.
	RetentionPeriod string `pulumi:"retentionPeriod"`
	// The Yandex Cloud Logging group status.
	Status string `pulumi:"status"`
}

func LookupLoggingGroupOutput(ctx *pulumi.Context, args LookupLoggingGroupOutputArgs, opts ...pulumi.InvokeOption) LookupLoggingGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupLoggingGroupResult, error) {
			args := v.(LookupLoggingGroupArgs)
			r, err := LookupLoggingGroup(ctx, &args, opts...)
			var s LookupLoggingGroupResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupLoggingGroupResultOutput)
}

// A collection of arguments for invoking getLoggingGroup.
type LookupLoggingGroupOutputArgs struct {
	// ID of the folder that the Yandex Cloud Logging group belongs to.
	// It will be deduced from provider configuration if not set explicitly.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// The Yandex Cloud Logging group ID.
	GroupId pulumi.StringPtrInput `pulumi:"groupId"`
	// The Yandex Cloud Logging group name.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupLoggingGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLoggingGroupArgs)(nil)).Elem()
}

// A collection of values returned by getLoggingGroup.
type LookupLoggingGroupResultOutput struct{ *pulumi.OutputState }

func (LookupLoggingGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLoggingGroupResult)(nil)).Elem()
}

func (o LookupLoggingGroupResultOutput) ToLookupLoggingGroupResultOutput() LookupLoggingGroupResultOutput {
	return o
}

func (o LookupLoggingGroupResultOutput) ToLookupLoggingGroupResultOutputWithContext(ctx context.Context) LookupLoggingGroupResultOutput {
	return o
}

// ID of the cloud that the Yandex Cloud Logging group belong to.
func (o LookupLoggingGroupResultOutput) CloudId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoggingGroupResult) string { return v.CloudId }).(pulumi.StringOutput)
}

// The Yandex Cloud Logging group creation timestamp.
func (o LookupLoggingGroupResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoggingGroupResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The Yandex Cloud Logging group description.
func (o LookupLoggingGroupResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoggingGroupResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupLoggingGroupResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoggingGroupResult) string { return v.FolderId }).(pulumi.StringOutput)
}

func (o LookupLoggingGroupResultOutput) GroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoggingGroupResult) string { return v.GroupId }).(pulumi.StringOutput)
}

func (o LookupLoggingGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoggingGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

// A set of key/value label pairs assigned to the Yandex Cloud Logging group.
func (o LookupLoggingGroupResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupLoggingGroupResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupLoggingGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoggingGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

// The Yandex Cloud Logging group log entries retention period.
func (o LookupLoggingGroupResultOutput) RetentionPeriod() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoggingGroupResult) string { return v.RetentionPeriod }).(pulumi.StringOutput)
}

// The Yandex Cloud Logging group status.
func (o LookupLoggingGroupResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLoggingGroupResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupLoggingGroupResultOutput{})
}
