// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about Yandex Cloud Lockbox secret version. For more information,
// see [the official documentation](https://cloud.yandex.com/en/docs/lockbox/).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"go.pact.im/x/tf2pulumi/yandex"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err = yandex.LookupLockboxSecretVersion(ctx, &GetLockboxSecretVersionArgs{
// 			SecretId: "some ID",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("mySecretEntries", data.Yandex_lockbox_secret.My_secret_version.Entries)
// 		return nil
// 	})
// }
// ```
func LookupLockboxSecretVersion(ctx *pulumi.Context, args *LookupLockboxSecretVersionArgs, opts ...pulumi.InvokeOption) (*LookupLockboxSecretVersionResult, error) {
	var rv LookupLockboxSecretVersionResult
	err := ctx.Invoke("yandex:index/getLockboxSecretVersion:getLockboxSecretVersion", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLockboxSecretVersion.
type LookupLockboxSecretVersionArgs struct {
	// The Yandex Cloud Lockbox secret ID.
	SecretId string `pulumi:"secretId"`
	// The Yandex Cloud Lockbox secret version ID.
	VersionId *string `pulumi:"versionId"`
}

// A collection of values returned by getLockboxSecretVersion.
type LookupLockboxSecretVersionResult struct {
	// List of entries in the Yandex Cloud Lockbox secret version.
	Entries   []GetLockboxSecretVersionEntry `pulumi:"entries"`
	Id        string                         `pulumi:"id"`
	SecretId  string                         `pulumi:"secretId"`
	VersionId string                         `pulumi:"versionId"`
}

func LookupLockboxSecretVersionOutput(ctx *pulumi.Context, args LookupLockboxSecretVersionOutputArgs, opts ...pulumi.InvokeOption) LookupLockboxSecretVersionResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupLockboxSecretVersionResult, error) {
			args := v.(LookupLockboxSecretVersionArgs)
			r, err := LookupLockboxSecretVersion(ctx, &args, opts...)
			var s LookupLockboxSecretVersionResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupLockboxSecretVersionResultOutput)
}

// A collection of arguments for invoking getLockboxSecretVersion.
type LookupLockboxSecretVersionOutputArgs struct {
	// The Yandex Cloud Lockbox secret ID.
	SecretId pulumi.StringInput `pulumi:"secretId"`
	// The Yandex Cloud Lockbox secret version ID.
	VersionId pulumi.StringPtrInput `pulumi:"versionId"`
}

func (LookupLockboxSecretVersionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLockboxSecretVersionArgs)(nil)).Elem()
}

// A collection of values returned by getLockboxSecretVersion.
type LookupLockboxSecretVersionResultOutput struct{ *pulumi.OutputState }

func (LookupLockboxSecretVersionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLockboxSecretVersionResult)(nil)).Elem()
}

func (o LookupLockboxSecretVersionResultOutput) ToLookupLockboxSecretVersionResultOutput() LookupLockboxSecretVersionResultOutput {
	return o
}

func (o LookupLockboxSecretVersionResultOutput) ToLookupLockboxSecretVersionResultOutputWithContext(ctx context.Context) LookupLockboxSecretVersionResultOutput {
	return o
}

// List of entries in the Yandex Cloud Lockbox secret version.
func (o LookupLockboxSecretVersionResultOutput) Entries() GetLockboxSecretVersionEntryArrayOutput {
	return o.ApplyT(func(v LookupLockboxSecretVersionResult) []GetLockboxSecretVersionEntry { return v.Entries }).(GetLockboxSecretVersionEntryArrayOutput)
}

func (o LookupLockboxSecretVersionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLockboxSecretVersionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupLockboxSecretVersionResultOutput) SecretId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLockboxSecretVersionResult) string { return v.SecretId }).(pulumi.StringOutput)
}

func (o LookupLockboxSecretVersionResultOutput) VersionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLockboxSecretVersionResult) string { return v.VersionId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupLockboxSecretVersionResultOutput{})
}
