// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex.Cloud Organization Manager Group. For more information, see
// [the official documentation](https://cloud.yandex.com/en-ru/docs/organization/manage-groups).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"go.pact.im/x/tf2pulumi/yandex"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		group, err := yandex.GetOrganizationmanagerGroup(ctx, &GetOrganizationmanagerGroupArgs{
// 			GroupId:        pulumi.StringRef("some_group_id"),
// 			OrganizationId: pulumi.StringRef("some_organization_id"),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("myGroup.name", group.Name)
// 		return nil
// 	})
// }
// ```
func GetOrganizationmanagerGroup(ctx *pulumi.Context, args *GetOrganizationmanagerGroupArgs, opts ...pulumi.InvokeOption) (*GetOrganizationmanagerGroupResult, error) {
	var rv GetOrganizationmanagerGroupResult
	err := ctx.Invoke("yandex:index/getOrganizationmanagerGroup:getOrganizationmanagerGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOrganizationmanagerGroup.
type GetOrganizationmanagerGroupArgs struct {
	// ID of a Group.
	GroupId *string `pulumi:"groupId"`
	// Name of a Group.
	Name *string `pulumi:"name"`
	// Organization that the Group belongs to. If value is omitted, the default provider organization is used.
	OrganizationId *string `pulumi:"organizationId"`
}

// A collection of values returned by getOrganizationmanagerGroup.
type GetOrganizationmanagerGroupResult struct {
	// The Group creation timestamp.
	CreatedAt string `pulumi:"createdAt"`
	// The description of the Group.
	Description string `pulumi:"description"`
	GroupId     string `pulumi:"groupId"`
	// The ID of the member.
	Id string `pulumi:"id"`
	// A list of members of the Group. The structure is documented below.
	Members        []GetOrganizationmanagerGroupMember `pulumi:"members"`
	Name           string                              `pulumi:"name"`
	OrganizationId *string                             `pulumi:"organizationId"`
}

func GetOrganizationmanagerGroupOutput(ctx *pulumi.Context, args GetOrganizationmanagerGroupOutputArgs, opts ...pulumi.InvokeOption) GetOrganizationmanagerGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetOrganizationmanagerGroupResult, error) {
			args := v.(GetOrganizationmanagerGroupArgs)
			r, err := GetOrganizationmanagerGroup(ctx, &args, opts...)
			var s GetOrganizationmanagerGroupResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetOrganizationmanagerGroupResultOutput)
}

// A collection of arguments for invoking getOrganizationmanagerGroup.
type GetOrganizationmanagerGroupOutputArgs struct {
	// ID of a Group.
	GroupId pulumi.StringPtrInput `pulumi:"groupId"`
	// Name of a Group.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Organization that the Group belongs to. If value is omitted, the default provider organization is used.
	OrganizationId pulumi.StringPtrInput `pulumi:"organizationId"`
}

func (GetOrganizationmanagerGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOrganizationmanagerGroupArgs)(nil)).Elem()
}

// A collection of values returned by getOrganizationmanagerGroup.
type GetOrganizationmanagerGroupResultOutput struct{ *pulumi.OutputState }

func (GetOrganizationmanagerGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOrganizationmanagerGroupResult)(nil)).Elem()
}

func (o GetOrganizationmanagerGroupResultOutput) ToGetOrganizationmanagerGroupResultOutput() GetOrganizationmanagerGroupResultOutput {
	return o
}

func (o GetOrganizationmanagerGroupResultOutput) ToGetOrganizationmanagerGroupResultOutputWithContext(ctx context.Context) GetOrganizationmanagerGroupResultOutput {
	return o
}

// The Group creation timestamp.
func (o GetOrganizationmanagerGroupResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerGroupResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The description of the Group.
func (o GetOrganizationmanagerGroupResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerGroupResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetOrganizationmanagerGroupResultOutput) GroupId() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerGroupResult) string { return v.GroupId }).(pulumi.StringOutput)
}

// The ID of the member.
func (o GetOrganizationmanagerGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

// A list of members of the Group. The structure is documented below.
func (o GetOrganizationmanagerGroupResultOutput) Members() GetOrganizationmanagerGroupMemberArrayOutput {
	return o.ApplyT(func(v GetOrganizationmanagerGroupResult) []GetOrganizationmanagerGroupMember { return v.Members }).(GetOrganizationmanagerGroupMemberArrayOutput)
}

func (o GetOrganizationmanagerGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetOrganizationmanagerGroupResultOutput) OrganizationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetOrganizationmanagerGroupResult) *string { return v.OrganizationId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOrganizationmanagerGroupResultOutput{})
}
