// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex SAML Federation. For more information, see
// [the official documentation](https://cloud.yandex.com/docs/organization/add-federation).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"go.pact.im/x/tf2pulumi/yandex"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		federation, err := yandex.GetOrganizationmanagerSamlFederation(ctx, &GetOrganizationmanagerSamlFederationArgs{
// 			FederationId:   pulumi.StringRef("some_federation_id"),
// 			OrganizationId: pulumi.StringRef("some_organization_id"),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("myFederation.name", federation.Name)
// 		return nil
// 	})
// }
// ```
func GetOrganizationmanagerSamlFederation(ctx *pulumi.Context, args *GetOrganizationmanagerSamlFederationArgs, opts ...pulumi.InvokeOption) (*GetOrganizationmanagerSamlFederationResult, error) {
	var rv GetOrganizationmanagerSamlFederationResult
	err := ctx.Invoke("yandex:index/getOrganizationmanagerSamlFederation:getOrganizationmanagerSamlFederation", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOrganizationmanagerSamlFederation.
type GetOrganizationmanagerSamlFederationArgs struct {
	// ID of a SAML Federation.
	FederationId *string `pulumi:"federationId"`
	// A set of key/value label pairs assigned to the SAML Federation.
	Labels map[string]string `pulumi:"labels"`
	// Name of a SAML Federation.
	Name *string `pulumi:"name"`
	// Organization that the federation belongs to. If value is omitted, the default provider organization is used.
	OrganizationId *string `pulumi:"organizationId"`
}

// A collection of values returned by getOrganizationmanagerSamlFederation.
type GetOrganizationmanagerSamlFederationResult struct {
	// Indicates whether new users get added automatically on successful authentication.
	AutoCreateAccountOnLogin bool `pulumi:"autoCreateAccountOnLogin"`
	// Indicates whether case-insensitive name ids are in use.
	CaseInsensitiveNameIds bool `pulumi:"caseInsensitiveNameIds"`
	// The lifetime of a Browser cookie in seconds.
	CookieMaxAge string `pulumi:"cookieMaxAge"`
	// The SAML Federation creation timestamp.
	CreatedAt string `pulumi:"createdAt"`
	// The description of the SAML Federation.
	Description  string `pulumi:"description"`
	FederationId string `pulumi:"federationId"`
	Id           string `pulumi:"id"`
	// The ID of the IdP server used for authentication.
	Issuer string `pulumi:"issuer"`
	// A set of key/value label pairs assigned to the SAML Federation.
	Labels         map[string]string `pulumi:"labels"`
	Name           string            `pulumi:"name"`
	OrganizationId *string           `pulumi:"organizationId"`
	// Federation security settings, structure is documented below.
	SecuritySettings []GetOrganizationmanagerSamlFederationSecuritySetting `pulumi:"securitySettings"`
	// Single sign-on endpoint binding type.
	SsoBinding string `pulumi:"ssoBinding"`
	// Single sign-on endpoint URL.
	SsoUrl string `pulumi:"ssoUrl"`
}

func GetOrganizationmanagerSamlFederationOutput(ctx *pulumi.Context, args GetOrganizationmanagerSamlFederationOutputArgs, opts ...pulumi.InvokeOption) GetOrganizationmanagerSamlFederationResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetOrganizationmanagerSamlFederationResult, error) {
			args := v.(GetOrganizationmanagerSamlFederationArgs)
			r, err := GetOrganizationmanagerSamlFederation(ctx, &args, opts...)
			var s GetOrganizationmanagerSamlFederationResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetOrganizationmanagerSamlFederationResultOutput)
}

// A collection of arguments for invoking getOrganizationmanagerSamlFederation.
type GetOrganizationmanagerSamlFederationOutputArgs struct {
	// ID of a SAML Federation.
	FederationId pulumi.StringPtrInput `pulumi:"federationId"`
	// A set of key/value label pairs assigned to the SAML Federation.
	Labels pulumi.StringMapInput `pulumi:"labels"`
	// Name of a SAML Federation.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Organization that the federation belongs to. If value is omitted, the default provider organization is used.
	OrganizationId pulumi.StringPtrInput `pulumi:"organizationId"`
}

func (GetOrganizationmanagerSamlFederationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOrganizationmanagerSamlFederationArgs)(nil)).Elem()
}

// A collection of values returned by getOrganizationmanagerSamlFederation.
type GetOrganizationmanagerSamlFederationResultOutput struct{ *pulumi.OutputState }

func (GetOrganizationmanagerSamlFederationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOrganizationmanagerSamlFederationResult)(nil)).Elem()
}

func (o GetOrganizationmanagerSamlFederationResultOutput) ToGetOrganizationmanagerSamlFederationResultOutput() GetOrganizationmanagerSamlFederationResultOutput {
	return o
}

func (o GetOrganizationmanagerSamlFederationResultOutput) ToGetOrganizationmanagerSamlFederationResultOutputWithContext(ctx context.Context) GetOrganizationmanagerSamlFederationResultOutput {
	return o
}

// Indicates whether new users get added automatically on successful authentication.
func (o GetOrganizationmanagerSamlFederationResultOutput) AutoCreateAccountOnLogin() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) bool { return v.AutoCreateAccountOnLogin }).(pulumi.BoolOutput)
}

// Indicates whether case-insensitive name ids are in use.
func (o GetOrganizationmanagerSamlFederationResultOutput) CaseInsensitiveNameIds() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) bool { return v.CaseInsensitiveNameIds }).(pulumi.BoolOutput)
}

// The lifetime of a Browser cookie in seconds.
func (o GetOrganizationmanagerSamlFederationResultOutput) CookieMaxAge() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) string { return v.CookieMaxAge }).(pulumi.StringOutput)
}

// The SAML Federation creation timestamp.
func (o GetOrganizationmanagerSamlFederationResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The description of the SAML Federation.
func (o GetOrganizationmanagerSamlFederationResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetOrganizationmanagerSamlFederationResultOutput) FederationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) string { return v.FederationId }).(pulumi.StringOutput)
}

func (o GetOrganizationmanagerSamlFederationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) string { return v.Id }).(pulumi.StringOutput)
}

// The ID of the IdP server used for authentication.
func (o GetOrganizationmanagerSamlFederationResultOutput) Issuer() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) string { return v.Issuer }).(pulumi.StringOutput)
}

// A set of key/value label pairs assigned to the SAML Federation.
func (o GetOrganizationmanagerSamlFederationResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o GetOrganizationmanagerSamlFederationResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetOrganizationmanagerSamlFederationResultOutput) OrganizationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) *string { return v.OrganizationId }).(pulumi.StringPtrOutput)
}

// Federation security settings, structure is documented below.
func (o GetOrganizationmanagerSamlFederationResultOutput) SecuritySettings() GetOrganizationmanagerSamlFederationSecuritySettingArrayOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) []GetOrganizationmanagerSamlFederationSecuritySetting {
		return v.SecuritySettings
	}).(GetOrganizationmanagerSamlFederationSecuritySettingArrayOutput)
}

// Single sign-on endpoint binding type.
func (o GetOrganizationmanagerSamlFederationResultOutput) SsoBinding() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) string { return v.SsoBinding }).(pulumi.StringOutput)
}

// Single sign-on endpoint URL.
func (o GetOrganizationmanagerSamlFederationResultOutput) SsoUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationmanagerSamlFederationResult) string { return v.SsoUrl }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOrganizationmanagerSamlFederationResultOutput{})
}
