// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Cloud Serverless Container.
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"go.pact.im/x/tf2pulumi/yandex"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err = yandex.LookupServerlessContainer(ctx, &GetServerlessContainerArgs{
// 			ContainerId: pulumi.StringRef("are1samplecontainer11"),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// This data source is used to define Yandex Cloud Container that can be used by other resources.
func LookupServerlessContainer(ctx *pulumi.Context, args *LookupServerlessContainerArgs, opts ...pulumi.InvokeOption) (*LookupServerlessContainerResult, error) {
	var rv LookupServerlessContainerResult
	err := ctx.Invoke("yandex:index/getServerlessContainer:getServerlessContainer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServerlessContainer.
type LookupServerlessContainerArgs struct {
	// Yandex Cloud Serverless Container id used to define container
	ContainerId *string `pulumi:"containerId"`
	// Folder ID for the Yandex Cloud Serverless Container
	FolderId *string `pulumi:"folderId"`
	// Yandex Cloud Serverless Container name used to define container
	Name *string `pulumi:"name"`
	// Secrets for Yandex Cloud Serverless Container
	// * `image.0.url` - URL of image that deployed as Yandex Cloud Serverless Container
	// * `image.0.work_dir` - Working directory of Yandex Cloud Serverless Container
	// * `image.0.digest` - Digest of image that deployed as Yandex Cloud Serverless Container
	// * `image.0.command` - List of commands of the Yandex Cloud Serverless Container
	// * `image.0.args` - List of arguments of the Yandex Cloud Serverless Container
	// * `image.0.environment` -  A set of key/value environment variable pairs of Yandex Cloud Serverless Container
	Secrets []GetServerlessContainerSecret `pulumi:"secrets"`
}

// A collection of values returned by getServerlessContainer.
type LookupServerlessContainerResult struct {
	// Concurrency of Yandex Cloud Serverless Container
	Concurrency float64 `pulumi:"concurrency"`
	ContainerId *string `pulumi:"containerId"`
	// Core fraction (**0...100**) of the Yandex Cloud Serverless Container
	CoreFraction float64 `pulumi:"coreFraction"`
	Cores        float64 `pulumi:"cores"`
	// Creation timestamp of the Yandex Cloud Serverless Container
	CreatedAt string `pulumi:"createdAt"`
	// Description of the Yandex Cloud Serverless Container
	Description string `pulumi:"description"`
	// Execution timeout (duration format) of Yandex Cloud Serverless Container
	ExecutionTimeout string                        `pulumi:"executionTimeout"`
	FolderId         *string                       `pulumi:"folderId"`
	Id               string                        `pulumi:"id"`
	Images           []GetServerlessContainerImage `pulumi:"images"`
	// A set of key/value label pairs assigned to the Yandex Cloud Serverless Container
	Labels map[string]string `pulumi:"labels"`
	// Memory in megabytes of Yandex Cloud Serverless Container
	Memory float64 `pulumi:"memory"`
	Name   *string `pulumi:"name"`
	// Last revision ID of the Yandex Cloud Serverless Container
	RevisionId string `pulumi:"revisionId"`
	// Secrets for Yandex Cloud Serverless Container
	// * `image.0.url` - URL of image that deployed as Yandex Cloud Serverless Container
	// * `image.0.work_dir` - Working directory of Yandex Cloud Serverless Container
	// * `image.0.digest` - Digest of image that deployed as Yandex Cloud Serverless Container
	// * `image.0.command` - List of commands of the Yandex Cloud Serverless Container
	// * `image.0.args` - List of arguments of the Yandex Cloud Serverless Container
	// * `image.0.environment` -  A set of key/value environment variable pairs of Yandex Cloud Serverless Container
	Secrets []GetServerlessContainerSecret `pulumi:"secrets"`
	// Service account ID of Yandex Cloud Serverless Container
	ServiceAccountId string `pulumi:"serviceAccountId"`
	// Invoke URL of the Yandex Cloud Serverless Container
	Url string `pulumi:"url"`
}

func LookupServerlessContainerOutput(ctx *pulumi.Context, args LookupServerlessContainerOutputArgs, opts ...pulumi.InvokeOption) LookupServerlessContainerResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupServerlessContainerResult, error) {
			args := v.(LookupServerlessContainerArgs)
			r, err := LookupServerlessContainer(ctx, &args, opts...)
			var s LookupServerlessContainerResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupServerlessContainerResultOutput)
}

// A collection of arguments for invoking getServerlessContainer.
type LookupServerlessContainerOutputArgs struct {
	// Yandex Cloud Serverless Container id used to define container
	ContainerId pulumi.StringPtrInput `pulumi:"containerId"`
	// Folder ID for the Yandex Cloud Serverless Container
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// Yandex Cloud Serverless Container name used to define container
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Secrets for Yandex Cloud Serverless Container
	// * `image.0.url` - URL of image that deployed as Yandex Cloud Serverless Container
	// * `image.0.work_dir` - Working directory of Yandex Cloud Serverless Container
	// * `image.0.digest` - Digest of image that deployed as Yandex Cloud Serverless Container
	// * `image.0.command` - List of commands of the Yandex Cloud Serverless Container
	// * `image.0.args` - List of arguments of the Yandex Cloud Serverless Container
	// * `image.0.environment` -  A set of key/value environment variable pairs of Yandex Cloud Serverless Container
	Secrets GetServerlessContainerSecretArrayInput `pulumi:"secrets"`
}

func (LookupServerlessContainerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServerlessContainerArgs)(nil)).Elem()
}

// A collection of values returned by getServerlessContainer.
type LookupServerlessContainerResultOutput struct{ *pulumi.OutputState }

func (LookupServerlessContainerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServerlessContainerResult)(nil)).Elem()
}

func (o LookupServerlessContainerResultOutput) ToLookupServerlessContainerResultOutput() LookupServerlessContainerResultOutput {
	return o
}

func (o LookupServerlessContainerResultOutput) ToLookupServerlessContainerResultOutputWithContext(ctx context.Context) LookupServerlessContainerResultOutput {
	return o
}

// Concurrency of Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Concurrency() pulumi.Float64Output {
	return o.ApplyT(func(v LookupServerlessContainerResult) float64 { return v.Concurrency }).(pulumi.Float64Output)
}

func (o LookupServerlessContainerResultOutput) ContainerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *string { return v.ContainerId }).(pulumi.StringPtrOutput)
}

// Core fraction (**0...100**) of the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) CoreFraction() pulumi.Float64Output {
	return o.ApplyT(func(v LookupServerlessContainerResult) float64 { return v.CoreFraction }).(pulumi.Float64Output)
}

func (o LookupServerlessContainerResultOutput) Cores() pulumi.Float64Output {
	return o.ApplyT(func(v LookupServerlessContainerResult) float64 { return v.Cores }).(pulumi.Float64Output)
}

// Creation timestamp of the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Description of the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.Description }).(pulumi.StringOutput)
}

// Execution timeout (duration format) of Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) ExecutionTimeout() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.ExecutionTimeout }).(pulumi.StringOutput)
}

func (o LookupServerlessContainerResultOutput) FolderId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *string { return v.FolderId }).(pulumi.StringPtrOutput)
}

func (o LookupServerlessContainerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupServerlessContainerResultOutput) Images() GetServerlessContainerImageArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerImage { return v.Images }).(GetServerlessContainerImageArrayOutput)
}

// A set of key/value label pairs assigned to the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

// Memory in megabytes of Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Memory() pulumi.Float64Output {
	return o.ApplyT(func(v LookupServerlessContainerResult) float64 { return v.Memory }).(pulumi.Float64Output)
}

func (o LookupServerlessContainerResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// Last revision ID of the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) RevisionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.RevisionId }).(pulumi.StringOutput)
}

// Secrets for Yandex Cloud Serverless Container
// * `image.0.url` - URL of image that deployed as Yandex Cloud Serverless Container
// * `image.0.work_dir` - Working directory of Yandex Cloud Serverless Container
// * `image.0.digest` - Digest of image that deployed as Yandex Cloud Serverless Container
// * `image.0.command` - List of commands of the Yandex Cloud Serverless Container
// * `image.0.args` - List of arguments of the Yandex Cloud Serverless Container
// * `image.0.environment` -  A set of key/value environment variable pairs of Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Secrets() GetServerlessContainerSecretArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerSecret { return v.Secrets }).(GetServerlessContainerSecretArrayOutput)
}

// Service account ID of Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) ServiceAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.ServiceAccountId }).(pulumi.StringOutput)
}

// Invoke URL of the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupServerlessContainerResultOutput{})
}
