// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"errors"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Allows management of a single SAML Federation within an existing Yandex.Cloud Organization.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"go.pact.im/x/tf2pulumi/yandex"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := yandex.NewOrganizationManagerSamlFederation(ctx, "federation", &yandex.OrganizationManagerSamlFederationArgs{
// 			Description:    pulumi.String("My new SAML federation"),
// 			Issuer:         pulumi.String("my-issuer"),
// 			OrganizationId: pulumi.String("sdf4*********3fr"),
// 			SsoBinding:     pulumi.String("POST"),
// 			SsoUrl:         pulumi.String("https://my-sso.url"),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// A Yandex SAML Federation can be imported using the `id` of the resource, e.g.
//
// ```sh
//  $ pulumi import yandex:index/organizationManagerSamlFederation:OrganizationManagerSamlFederation federation "federation_id"
// ```
type OrganizationManagerSamlFederation struct {
	pulumi.CustomResourceState

	// Add new users automatically on successful authentication. The user will get the `resource-manager.clouds.member` role automatically, but you need to grant other roles to them. If the value is `false`, users who aren't added to the cloud can't log in, even if they have authenticated on your server.
	AutoCreateAccountOnLogin pulumi.BoolOutput `pulumi:"autoCreateAccountOnLogin"`
	// Use case-insensitive name ids.
	CaseInsensitiveNameIds pulumi.BoolOutput `pulumi:"caseInsensitiveNameIds"`
	// The lifetime of a Browser cookie in seconds. If the cookie is still valid, the management console authenticates the user immediately and redirects them to the home page. The default value is `8h`.
	CookieMaxAge pulumi.StringOutput `pulumi:"cookieMaxAge"`
	// (Computed) The SAML Federation creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The description of the SAML Federation.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The ID of the IdP server to be used for authentication. The IdP server also responds to IAM with this ID after the user authenticates.
	Issuer pulumi.StringOutput `pulumi:"issuer"`
	// A set of key/value label pairs assigned to the SAML Federation.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// The name of the SAML Federation.
	Name pulumi.StringOutput `pulumi:"name"`
	// The organization to attach this SAML Federation to.
	OrganizationId pulumi.StringOutput `pulumi:"organizationId"`
	// Federation security settings, structure is documented below.
	SecuritySettings OrganizationManagerSamlFederationSecuritySettingsPtrOutput `pulumi:"securitySettings"`
	// Single sign-on endpoint binding type. Most Identity Providers support the `POST` binding type. SAML Binding is a mapping of a SAML protocol message onto standard messaging formats and/or communications protocols.
	SsoBinding pulumi.StringOutput `pulumi:"ssoBinding"`
	// Single sign-on endpoint URL. Specify the link to the IdP login page here.
	SsoUrl   pulumi.StringOutput                             `pulumi:"ssoUrl"`
	Timeouts OrganizationManagerSamlFederationTimeoutsOutput `pulumi:"timeouts"`
}

// NewOrganizationManagerSamlFederation registers a new resource with the given unique name, arguments, and options.
func NewOrganizationManagerSamlFederation(ctx *pulumi.Context,
	name string, args *OrganizationManagerSamlFederationArgs, opts ...pulumi.ResourceOption) (*OrganizationManagerSamlFederation, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Issuer == nil {
		return nil, errors.New("invalid value for required argument 'Issuer'")
	}
	if args.OrganizationId == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationId'")
	}
	if args.SsoBinding == nil {
		return nil, errors.New("invalid value for required argument 'SsoBinding'")
	}
	if args.SsoUrl == nil {
		return nil, errors.New("invalid value for required argument 'SsoUrl'")
	}
	if args.Timeouts == nil {
		return nil, errors.New("invalid value for required argument 'Timeouts'")
	}
	var resource OrganizationManagerSamlFederation
	err := ctx.RegisterResource("yandex:index/organizationManagerSamlFederation:OrganizationManagerSamlFederation", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrganizationManagerSamlFederation gets an existing OrganizationManagerSamlFederation resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrganizationManagerSamlFederation(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrganizationManagerSamlFederationState, opts ...pulumi.ResourceOption) (*OrganizationManagerSamlFederation, error) {
	var resource OrganizationManagerSamlFederation
	err := ctx.ReadResource("yandex:index/organizationManagerSamlFederation:OrganizationManagerSamlFederation", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OrganizationManagerSamlFederation resources.
type organizationManagerSamlFederationState struct {
	// Add new users automatically on successful authentication. The user will get the `resource-manager.clouds.member` role automatically, but you need to grant other roles to them. If the value is `false`, users who aren't added to the cloud can't log in, even if they have authenticated on your server.
	AutoCreateAccountOnLogin *bool `pulumi:"autoCreateAccountOnLogin"`
	// Use case-insensitive name ids.
	CaseInsensitiveNameIds *bool `pulumi:"caseInsensitiveNameIds"`
	// The lifetime of a Browser cookie in seconds. If the cookie is still valid, the management console authenticates the user immediately and redirects them to the home page. The default value is `8h`.
	CookieMaxAge *string `pulumi:"cookieMaxAge"`
	// (Computed) The SAML Federation creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// The description of the SAML Federation.
	Description *string `pulumi:"description"`
	// The ID of the IdP server to be used for authentication. The IdP server also responds to IAM with this ID after the user authenticates.
	Issuer *string `pulumi:"issuer"`
	// A set of key/value label pairs assigned to the SAML Federation.
	Labels map[string]string `pulumi:"labels"`
	// The name of the SAML Federation.
	Name *string `pulumi:"name"`
	// The organization to attach this SAML Federation to.
	OrganizationId *string `pulumi:"organizationId"`
	// Federation security settings, structure is documented below.
	SecuritySettings *OrganizationManagerSamlFederationSecuritySettings `pulumi:"securitySettings"`
	// Single sign-on endpoint binding type. Most Identity Providers support the `POST` binding type. SAML Binding is a mapping of a SAML protocol message onto standard messaging formats and/or communications protocols.
	SsoBinding *string `pulumi:"ssoBinding"`
	// Single sign-on endpoint URL. Specify the link to the IdP login page here.
	SsoUrl   *string                                    `pulumi:"ssoUrl"`
	Timeouts *OrganizationManagerSamlFederationTimeouts `pulumi:"timeouts"`
}

type OrganizationManagerSamlFederationState struct {
	// Add new users automatically on successful authentication. The user will get the `resource-manager.clouds.member` role automatically, but you need to grant other roles to them. If the value is `false`, users who aren't added to the cloud can't log in, even if they have authenticated on your server.
	AutoCreateAccountOnLogin pulumi.BoolPtrInput
	// Use case-insensitive name ids.
	CaseInsensitiveNameIds pulumi.BoolPtrInput
	// The lifetime of a Browser cookie in seconds. If the cookie is still valid, the management console authenticates the user immediately and redirects them to the home page. The default value is `8h`.
	CookieMaxAge pulumi.StringPtrInput
	// (Computed) The SAML Federation creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// The description of the SAML Federation.
	Description pulumi.StringPtrInput
	// The ID of the IdP server to be used for authentication. The IdP server also responds to IAM with this ID after the user authenticates.
	Issuer pulumi.StringPtrInput
	// A set of key/value label pairs assigned to the SAML Federation.
	Labels pulumi.StringMapInput
	// The name of the SAML Federation.
	Name pulumi.StringPtrInput
	// The organization to attach this SAML Federation to.
	OrganizationId pulumi.StringPtrInput
	// Federation security settings, structure is documented below.
	SecuritySettings OrganizationManagerSamlFederationSecuritySettingsPtrInput
	// Single sign-on endpoint binding type. Most Identity Providers support the `POST` binding type. SAML Binding is a mapping of a SAML protocol message onto standard messaging formats and/or communications protocols.
	SsoBinding pulumi.StringPtrInput
	// Single sign-on endpoint URL. Specify the link to the IdP login page here.
	SsoUrl   pulumi.StringPtrInput
	Timeouts OrganizationManagerSamlFederationTimeoutsPtrInput
}

func (OrganizationManagerSamlFederationState) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationManagerSamlFederationState)(nil)).Elem()
}

type organizationManagerSamlFederationArgs struct {
	// Add new users automatically on successful authentication. The user will get the `resource-manager.clouds.member` role automatically, but you need to grant other roles to them. If the value is `false`, users who aren't added to the cloud can't log in, even if they have authenticated on your server.
	AutoCreateAccountOnLogin *bool `pulumi:"autoCreateAccountOnLogin"`
	// Use case-insensitive name ids.
	CaseInsensitiveNameIds *bool `pulumi:"caseInsensitiveNameIds"`
	// The lifetime of a Browser cookie in seconds. If the cookie is still valid, the management console authenticates the user immediately and redirects them to the home page. The default value is `8h`.
	CookieMaxAge *string `pulumi:"cookieMaxAge"`
	// The description of the SAML Federation.
	Description *string `pulumi:"description"`
	// The ID of the IdP server to be used for authentication. The IdP server also responds to IAM with this ID after the user authenticates.
	Issuer string `pulumi:"issuer"`
	// A set of key/value label pairs assigned to the SAML Federation.
	Labels map[string]string `pulumi:"labels"`
	// The name of the SAML Federation.
	Name *string `pulumi:"name"`
	// The organization to attach this SAML Federation to.
	OrganizationId string `pulumi:"organizationId"`
	// Federation security settings, structure is documented below.
	SecuritySettings *OrganizationManagerSamlFederationSecuritySettings `pulumi:"securitySettings"`
	// Single sign-on endpoint binding type. Most Identity Providers support the `POST` binding type. SAML Binding is a mapping of a SAML protocol message onto standard messaging formats and/or communications protocols.
	SsoBinding string `pulumi:"ssoBinding"`
	// Single sign-on endpoint URL. Specify the link to the IdP login page here.
	SsoUrl   string                                    `pulumi:"ssoUrl"`
	Timeouts OrganizationManagerSamlFederationTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a OrganizationManagerSamlFederation resource.
type OrganizationManagerSamlFederationArgs struct {
	// Add new users automatically on successful authentication. The user will get the `resource-manager.clouds.member` role automatically, but you need to grant other roles to them. If the value is `false`, users who aren't added to the cloud can't log in, even if they have authenticated on your server.
	AutoCreateAccountOnLogin pulumi.BoolPtrInput
	// Use case-insensitive name ids.
	CaseInsensitiveNameIds pulumi.BoolPtrInput
	// The lifetime of a Browser cookie in seconds. If the cookie is still valid, the management console authenticates the user immediately and redirects them to the home page. The default value is `8h`.
	CookieMaxAge pulumi.StringPtrInput
	// The description of the SAML Federation.
	Description pulumi.StringPtrInput
	// The ID of the IdP server to be used for authentication. The IdP server also responds to IAM with this ID after the user authenticates.
	Issuer pulumi.StringInput
	// A set of key/value label pairs assigned to the SAML Federation.
	Labels pulumi.StringMapInput
	// The name of the SAML Federation.
	Name pulumi.StringPtrInput
	// The organization to attach this SAML Federation to.
	OrganizationId pulumi.StringInput
	// Federation security settings, structure is documented below.
	SecuritySettings OrganizationManagerSamlFederationSecuritySettingsPtrInput
	// Single sign-on endpoint binding type. Most Identity Providers support the `POST` binding type. SAML Binding is a mapping of a SAML protocol message onto standard messaging formats and/or communications protocols.
	SsoBinding pulumi.StringInput
	// Single sign-on endpoint URL. Specify the link to the IdP login page here.
	SsoUrl   pulumi.StringInput
	Timeouts OrganizationManagerSamlFederationTimeoutsInput
}

func (OrganizationManagerSamlFederationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationManagerSamlFederationArgs)(nil)).Elem()
}

type OrganizationManagerSamlFederationInput interface {
	pulumi.Input

	ToOrganizationManagerSamlFederationOutput() OrganizationManagerSamlFederationOutput
	ToOrganizationManagerSamlFederationOutputWithContext(ctx context.Context) OrganizationManagerSamlFederationOutput
}

func (*OrganizationManagerSamlFederation) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationManagerSamlFederation)(nil)).Elem()
}

func (i *OrganizationManagerSamlFederation) ToOrganizationManagerSamlFederationOutput() OrganizationManagerSamlFederationOutput {
	return i.ToOrganizationManagerSamlFederationOutputWithContext(context.Background())
}

func (i *OrganizationManagerSamlFederation) ToOrganizationManagerSamlFederationOutputWithContext(ctx context.Context) OrganizationManagerSamlFederationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationManagerSamlFederationOutput)
}

// OrganizationManagerSamlFederationArrayInput is an input type that accepts OrganizationManagerSamlFederationArray and OrganizationManagerSamlFederationArrayOutput values.
// You can construct a concrete instance of `OrganizationManagerSamlFederationArrayInput` via:
//
//          OrganizationManagerSamlFederationArray{ OrganizationManagerSamlFederationArgs{...} }
type OrganizationManagerSamlFederationArrayInput interface {
	pulumi.Input

	ToOrganizationManagerSamlFederationArrayOutput() OrganizationManagerSamlFederationArrayOutput
	ToOrganizationManagerSamlFederationArrayOutputWithContext(context.Context) OrganizationManagerSamlFederationArrayOutput
}

type OrganizationManagerSamlFederationArray []OrganizationManagerSamlFederationInput

func (OrganizationManagerSamlFederationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OrganizationManagerSamlFederation)(nil)).Elem()
}

func (i OrganizationManagerSamlFederationArray) ToOrganizationManagerSamlFederationArrayOutput() OrganizationManagerSamlFederationArrayOutput {
	return i.ToOrganizationManagerSamlFederationArrayOutputWithContext(context.Background())
}

func (i OrganizationManagerSamlFederationArray) ToOrganizationManagerSamlFederationArrayOutputWithContext(ctx context.Context) OrganizationManagerSamlFederationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationManagerSamlFederationArrayOutput)
}

// OrganizationManagerSamlFederationMapInput is an input type that accepts OrganizationManagerSamlFederationMap and OrganizationManagerSamlFederationMapOutput values.
// You can construct a concrete instance of `OrganizationManagerSamlFederationMapInput` via:
//
//          OrganizationManagerSamlFederationMap{ "key": OrganizationManagerSamlFederationArgs{...} }
type OrganizationManagerSamlFederationMapInput interface {
	pulumi.Input

	ToOrganizationManagerSamlFederationMapOutput() OrganizationManagerSamlFederationMapOutput
	ToOrganizationManagerSamlFederationMapOutputWithContext(context.Context) OrganizationManagerSamlFederationMapOutput
}

type OrganizationManagerSamlFederationMap map[string]OrganizationManagerSamlFederationInput

func (OrganizationManagerSamlFederationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OrganizationManagerSamlFederation)(nil)).Elem()
}

func (i OrganizationManagerSamlFederationMap) ToOrganizationManagerSamlFederationMapOutput() OrganizationManagerSamlFederationMapOutput {
	return i.ToOrganizationManagerSamlFederationMapOutputWithContext(context.Background())
}

func (i OrganizationManagerSamlFederationMap) ToOrganizationManagerSamlFederationMapOutputWithContext(ctx context.Context) OrganizationManagerSamlFederationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationManagerSamlFederationMapOutput)
}

type OrganizationManagerSamlFederationOutput struct{ *pulumi.OutputState }

func (OrganizationManagerSamlFederationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationManagerSamlFederation)(nil)).Elem()
}

func (o OrganizationManagerSamlFederationOutput) ToOrganizationManagerSamlFederationOutput() OrganizationManagerSamlFederationOutput {
	return o
}

func (o OrganizationManagerSamlFederationOutput) ToOrganizationManagerSamlFederationOutputWithContext(ctx context.Context) OrganizationManagerSamlFederationOutput {
	return o
}

// Add new users automatically on successful authentication. The user will get the `resource-manager.clouds.member` role automatically, but you need to grant other roles to them. If the value is `false`, users who aren't added to the cloud can't log in, even if they have authenticated on your server.
func (o OrganizationManagerSamlFederationOutput) AutoCreateAccountOnLogin() pulumi.BoolOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.BoolOutput { return v.AutoCreateAccountOnLogin }).(pulumi.BoolOutput)
}

// Use case-insensitive name ids.
func (o OrganizationManagerSamlFederationOutput) CaseInsensitiveNameIds() pulumi.BoolOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.BoolOutput { return v.CaseInsensitiveNameIds }).(pulumi.BoolOutput)
}

// The lifetime of a Browser cookie in seconds. If the cookie is still valid, the management console authenticates the user immediately and redirects them to the home page. The default value is `8h`.
func (o OrganizationManagerSamlFederationOutput) CookieMaxAge() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.StringOutput { return v.CookieMaxAge }).(pulumi.StringOutput)
}

// (Computed) The SAML Federation creation timestamp.
func (o OrganizationManagerSamlFederationOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The description of the SAML Federation.
func (o OrganizationManagerSamlFederationOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The ID of the IdP server to be used for authentication. The IdP server also responds to IAM with this ID after the user authenticates.
func (o OrganizationManagerSamlFederationOutput) Issuer() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.StringOutput { return v.Issuer }).(pulumi.StringOutput)
}

// A set of key/value label pairs assigned to the SAML Federation.
func (o OrganizationManagerSamlFederationOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// The name of the SAML Federation.
func (o OrganizationManagerSamlFederationOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The organization to attach this SAML Federation to.
func (o OrganizationManagerSamlFederationOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.StringOutput { return v.OrganizationId }).(pulumi.StringOutput)
}

// Federation security settings, structure is documented below.
func (o OrganizationManagerSamlFederationOutput) SecuritySettings() OrganizationManagerSamlFederationSecuritySettingsPtrOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) OrganizationManagerSamlFederationSecuritySettingsPtrOutput {
		return v.SecuritySettings
	}).(OrganizationManagerSamlFederationSecuritySettingsPtrOutput)
}

// Single sign-on endpoint binding type. Most Identity Providers support the `POST` binding type. SAML Binding is a mapping of a SAML protocol message onto standard messaging formats and/or communications protocols.
func (o OrganizationManagerSamlFederationOutput) SsoBinding() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.StringOutput { return v.SsoBinding }).(pulumi.StringOutput)
}

// Single sign-on endpoint URL. Specify the link to the IdP login page here.
func (o OrganizationManagerSamlFederationOutput) SsoUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) pulumi.StringOutput { return v.SsoUrl }).(pulumi.StringOutput)
}

func (o OrganizationManagerSamlFederationOutput) Timeouts() OrganizationManagerSamlFederationTimeoutsOutput {
	return o.ApplyT(func(v *OrganizationManagerSamlFederation) OrganizationManagerSamlFederationTimeoutsOutput {
		return v.Timeouts
	}).(OrganizationManagerSamlFederationTimeoutsOutput)
}

type OrganizationManagerSamlFederationArrayOutput struct{ *pulumi.OutputState }

func (OrganizationManagerSamlFederationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OrganizationManagerSamlFederation)(nil)).Elem()
}

func (o OrganizationManagerSamlFederationArrayOutput) ToOrganizationManagerSamlFederationArrayOutput() OrganizationManagerSamlFederationArrayOutput {
	return o
}

func (o OrganizationManagerSamlFederationArrayOutput) ToOrganizationManagerSamlFederationArrayOutputWithContext(ctx context.Context) OrganizationManagerSamlFederationArrayOutput {
	return o
}

func (o OrganizationManagerSamlFederationArrayOutput) Index(i pulumi.IntInput) OrganizationManagerSamlFederationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *OrganizationManagerSamlFederation {
		return vs[0].([]*OrganizationManagerSamlFederation)[vs[1].(int)]
	}).(OrganizationManagerSamlFederationOutput)
}

type OrganizationManagerSamlFederationMapOutput struct{ *pulumi.OutputState }

func (OrganizationManagerSamlFederationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OrganizationManagerSamlFederation)(nil)).Elem()
}

func (o OrganizationManagerSamlFederationMapOutput) ToOrganizationManagerSamlFederationMapOutput() OrganizationManagerSamlFederationMapOutput {
	return o
}

func (o OrganizationManagerSamlFederationMapOutput) ToOrganizationManagerSamlFederationMapOutputWithContext(ctx context.Context) OrganizationManagerSamlFederationMapOutput {
	return o
}

func (o OrganizationManagerSamlFederationMapOutput) MapIndex(k pulumi.StringInput) OrganizationManagerSamlFederationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *OrganizationManagerSamlFederation {
		return vs[0].(map[string]*OrganizationManagerSamlFederation)[vs[1].(string)]
	}).(OrganizationManagerSamlFederationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationManagerSamlFederationInput)(nil)).Elem(), &OrganizationManagerSamlFederation{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationManagerSamlFederationArrayInput)(nil)).Elem(), OrganizationManagerSamlFederationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationManagerSamlFederationMapInput)(nil)).Elem(), OrganizationManagerSamlFederationMap{})
	pulumi.RegisterOutputType(OrganizationManagerSamlFederationOutput{})
	pulumi.RegisterOutputType(OrganizationManagerSamlFederationArrayOutput{})
	pulumi.RegisterOutputType(OrganizationManagerSamlFederationMapOutput{})
}
