name: 'Read file'
description: 'Read file contents from filesystem'
inputs:
  path:
    description: 'File path'
    required: true
  encoding:
    description: 'File encoding'
    required: false
    default: 'utf8'
outputs:
  content:
    description: 'File contents'
    value: ${{ steps.read-file.outputs.content }}
runs:
  using: composite
  steps:
    - name: Run script
      uses: actions/github-script@v6.1.0
      id: read-file
      with:
        script: |-
          const { promises: fs } = require('fs')
          const content = await fs.readFile(${{ toJSON(inputs.path) }}, ${{ toJSON(inputs.encoding) }})
          core.setOutput('content', content)
