name: 'Read file'
description: 'Read file contents from filesystem'
inputs:
  path:
    description: 'File path'
    required: true
  encoding:
    description: 'File encoding'
    required: false
    default: 'utf8'
  delete:
    description: 'Remove file after reading it'
    type: boolean
    required: false
    default: false
outputs:
  content:
    description: 'File contents'
    value: ${{ steps.read-file.outputs.content }}
runs:
  using: composite
  steps:
    - name: Run script
      uses: actions/github-script@v6.3.3
      id: read-file
      with:
        script: |-
          const { promises: fs } = require('fs')
          const filePath = ${{ toJSON(inputs.path) }}
          const content = await fs.readFile(filePath, ${{ toJSON(inputs.encoding) }})
          core.setOutput('content', content)
          if (${{ toJSON(inputs.delete) }}) {
            await fs.unlink(filePath)
          }
