name: Pages
on:
  push:
    branches:
      - main
    paths:
      - vangen.json
  schedule:
    # At 06:00 UTC on Monday.
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      GOWORK: ${{ github.workspace }}/go.work.example
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
      - name: Set up Go
        uses: ./.github/actions/setup-go-with-cache
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6.0.0
      - name: Build pages
        run: |-
          go tool vangen -out build
          go tool golds -dir=build/doc -gen -silent -footer=simple -wdpkgs-listing=solo work
          touch build/.nojekyll
          cat >build/404.html <<'EOF'
          <!doctype html>
          <!--
            The following meta go-import is for Go modules in private monorepo.
            Note that this file is a valid XML; see https://go.dev/issue/39748
            In addition to that, it should be safe to respond with 404, see
            https://groups.google.com/d/topic/golang-nuts/1kewLH-Vack
          -->
          <meta name="go-import" content="go.pact.im/private git https://github.com/pact-im/pact-go">
          <title>Page not found</title>
          <pre>404 page not found</pre>
          EOF
          echo go.pact.im >build/CNAME
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: build
          include-hidden-files: true
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
